import random
from pymongo import MongoClient
from bson.objectid import ObjectId

# IDs dos vendedores 
seller_ids = [
    ObjectId("67217ebd82bf91cb6d5ad7df"),
    ObjectId("671a76b8c4b1b2ae753e99e9"),
    ObjectId("671a45fa273f1130cfa4fe76"),
    ObjectId("671a3497b95fd2e609fafe15"),
    ObjectId("67193a390ef3926db6aaf8d6"),
]

# Conecta ao MongoDB usando o MONGO_URI fornecido
MONGO_URI = "mongodb+srv://henrique:123@cluster0.juves.mongodb.net/WebPecas?retryWrites=true&w=majority"

client = MongoClient(MONGO_URI)
db = client["WebPecas"]  # O nome do banco de dados é 'WebPecas', conforme o MONGO_URI
collection = db["products"]  #nome da colecao de produtos

# Dados para geração
car_brands_models = {
    "Chevrolet": [
        "Celta",
        "Corsa",
        "Prisma",
        "Onix",
        "Onix Plus",
        "Spin",
        "Tracker",
        "Cruze",
        "Cruze Sport6",
        "Montana",
        "S10",
        "Blazer",
        "Trailblazer",
        "Captiva",
        "Astra",
        "Vectra",
        "Omega",
        "Cobalt",
        "Meriva",
        "Zafira",
        "Agile",
        "Kadett",
        "Opala",
        "Chevette",
        "Monza",
    ],
    "Fiat": [
        "Uno",
        "Palio",
        "Palio Weekend",
        "Siena",
        "Grand Siena",
        "Strada",
        "Toro",
        "Mobi",
        "Argo",
        "Cronos",
        "Fiorino",
        "Doblò",
        "Idea",
        "Linea",
        "Bravo",
        "Punto",
        "500",
        "Stilo",
        "Tempra",
        "Tipo",
        "Ducato",
        "147",
        "Oggi",
        "Premio",
        "Elba",
    ],
    "Ford": [
        "Ka",
        "Ka Sedan",
        "Fiesta",
        "Fiesta Sedan",
        "EcoSport",
        "Fusion",
        "Focus",
        "Focus Sedan",
        "Ranger",
        "Maverick",
        "Corcel",
        "Del Rey",
        "Escort",
        "Verona",
        "Belina",
        "Pampa",
        "F-1000",
        "F-250",
        "Mustang",
        "Edge",
        "Territory",
    ],
    "Honda": [
        "Civic",
        "Fit",
        "City",
        "HR-V",
        "WR-V",
        "CR-V",
        "Accord",
        "NSX",
        "Prelude",
        "Odyssey",
        "Passport",
    ],
    "Hyundai": [
        "HB20",
        "HB20S",
        "Creta",
        "Tucson",
        "Santa Fe",
        "i30",
        "Elantra",
        "Azera",
        "Vera Cruz",
        "IX35",
        "Sonata",
        "Galloper",
    ],
    "Mitsubishi": [
        "Lancer",
        "ASX",
        "Outlander",
        "Pajero TR4",
        "Pajero Full",
        "Pajero Sport",
        "Eclipse Cross",
        "L200 Triton",
        "Eclipse",
        "Galant",
        "Mirage",
    ],
    "Renault": [
        "Kwid",
        "Sandero",
        "Logan",
        "Duster",
        "Oroch",
        "Captur",
        "Megane",
        "Fluence",
        "Scenic",
        "Clio",
        "Symbol",
        "Safrane",
        "Master",
        "Kangoo",
        "Twingo",
    ],
    "Toyota": [
        "Corolla",
        "Corolla Cross",
        "Yaris",
        "Yaris Sedan",
        "Etios",
        "Etios Sedan",
        "Hilux",
        "SW4",
        "Camry",
        "Prius",
        "RAV4",
        "Land Cruiser",
        "FJ Cruiser",
        "Bandeirante",
    ],
    "Volkswagen": [
        "Fusca",
        "Gol",
        "Voyage",
        "Parati",
        "Saveiro",
        "Kombi",
        "Brasília",
        "Santana",
        "Passat",
        "Pointer",
        "Apollo",
        "Fox",
        "SpaceFox",
        "Polo",
        "Golf",
        "Jetta",
        "Virtus",
        "Tiguan",
        "T-Cross",
        "Taos",
        "Amarok",
        "SP2",
        "CrossFox",
        "Nivus",
        "Up!",
        "Passat Variant",
        "Passat CC",
        "Bora",
        "Constellation",
        "Sharan",
        "Touareg",
        "Eos",
    ],
}

type_categories_parts = {
    "Motor e Sistema de Alimentação": [
        "Bloco do motor",
        "Cabeçote",
        "Velas de ignição",
        "Pistões",
        "Anéis de pistão",
        "Bielas",
        "Virabrequim",
        "Cárter",
        "Coletor de admissão",
        "Filtro de ar",
        "Turbocompressor",
        "Intercooler",
        "Injetores de combustível",
        "Bomba de combustível",
        "Filtro de combustível",
        "Válvulas de admissão e escape",
        "Corrente de distribuição",
        "Correia dentada",
        "Tuchos hidráulicos",
        "Radiador",
        "Ventoinha",
        "Termostato",
        "Bomba d’água",
        "Mangueiras de radiador",
        "Reservatório de expansão",
    ],
    "Transmissão e Embreagem": [
        "Caixa de câmbio (manual ou automática)",
        "Embreagem",
        "Disco de embreagem",
        "Placa de pressão",
        "Rolamento de embreagem",
        "Cabo de embreagem",
        "Conversor de torque",
        "Eixo de transmissão",
        "Diferencial",
        "Cardã",
        "Semi-eixos",
        "Juntas homocinéticas",
    ],
    "Suspensão": [
        "Amortecedores",
        "Molas helicoidais",
        "Molas a ar",
        "Barras estabilizadoras",
        "Braços de suspensão",
        "Buchas de suspensão",
        "Pivôs de suspensão",
        "Bieletas",
        "Mancais de roda",
        "Rolamentos de roda",
        "Batentes de suspensão",
    ],
    "Freios": [
        "Discos de freio",
        "Pastilhas de freio",
        "Tambor de freio",
        "Sapatas de freio",
        "Cilindro mestre",
        "Servo-freio",
        "Cilindro de roda",
        "Pinças de freio",
        "Fios e cabos de freio",
        "Mangueiras de freio",
        "Fluido de freio",
        "ABS (Sistema de freio antibloqueio)",
    ],
    "Direção": [
        "Caixa de direção (mecânica ou hidráulica)",
        "Coluna de direção",
        "Volante",
        "Braços de direção",
        "Barras de direção",
        "Caixa de direção elétrica (EPS)",
        "Juntas universais de direção",
        "Bomba da direção hidráulica",
        "Reservatório de fluido de direção",
        "Manga de eixo",
    ],
    "Rodas e Pneus": [
        "Rodas",
        "Pneus",
        "Câmaras de ar (para pneus com câmaras)",
        "Calotas",
        "Parafusos de roda",
        "Porcas de roda",
        "Macaco hidráulico",
        "Estepe",
        "Sensor de pressão dos pneus (TPMS)",
    ],
    "Sistema Elétrico": [
        "Alternador",
        "Bateria",
        "Motor de arranque",
        "Relés",
        "Fusíveis",
        "Caixa de fusíveis",
        "Velas de ignição",
        "Cabos de vela",
        "Chicote elétrico",
        "Central de injeção eletrônica (ECU)",
        "Sensor de oxigênio (sonda lambda)",
        "Sensor de temperatura",
        "Sensor de rotação",
        "Sensor MAP",
        "Sensor MAF",
        "Bobinas de ignição",
        "Interruptores e chaves (faróis, vidro elétrico, etc.)",
    ],
    "Iluminação e Sinalização": [
        "Faróis dianteiros",
        "Lâmpadas de farol",
        "Lanternas traseiras",
        "Faróis de neblina",
        "Pisca-pisca",
        "Luz de ré",
        "Luz de freio",
        "Luz de placa",
        "Farol alto/baixo",
        "Faróis de LED ou Xenon",
        "Refletores traseiros",
    ],
    "Interior e Acessórios": [
        "Painel de instrumentos",
        "Bancos",
        "Cintos de segurança",
        "Volante",
        "Alavanca de câmbio",
        "Pedais (acelerador, freio, embreagem)",
        "Tapetes automotivos",
        "Porta-luvas",
        "Console central",
        "Ar-condicionado",
        "Aquecedor",
        "Sistema de som",
        "Central multimídia",
        "Retrovisores internos",
        "Retrovisores externos",
        "Vidros elétricos",
        "Travas elétricas",
        "Chave de ignição",
        "Airbags",
    ],
    "Carroceria e Estrutura": [
        "Parachoques",
        "Capô",
        "Portas",
        "Porta-malas",
        "Paralamas",
        "Teto solar",
        "Para-brisas",
        "Vidros laterais",
        "Vidro traseiro",
        "Retrovisores",
        "Estrutura do chassi",
        "Assoalho",
        "Colunas A, B e C",
        "Vigas de impacto lateral",
    ],
    "Sistema de Escape": [
        "Escapamento",
        "Catalisador",
        "Sonda lambda",
        "Silenciador",
        "Coletor de escape",
        "Tubo intermediário",
        "Filtro de partículas (DPF)",
    ],
    "Outros Componentes": [
        "Reservatório de óleo",
        "Macaco",
        "Triângulo de sinalização",
        "Extintor de incêndio",
        "Limpadores de para-brisa",
        "Palhetas",
        "Reservatório de fluido de para-brisa",
        "Buzina",
    ],
}

conditions = ["nova", "usada"]
descriptions = [
    "Peça em excelente estado.",
    "Produto novo, nunca utilizado.",
    "Leve desgaste, mas funcionando perfeitamente.",
    "Peça original de fábrica.",
    "Revisado e testado.",
]

def generate_random_product():
    # Escolher vendedor aleatoriamente
    vendedor = random.choice(seller_ids)
    
    # Escolher categoria e peça
    typeCategory = random.choice(list(type_categories_parts.keys()))
    typePart = random.choice(type_categories_parts[typeCategory])
    
    # Escolher marca e modelo do carro
    carBrand = random.choice(list(car_brands_models.keys()))
    carModel = random.choice(car_brands_models[carBrand])
    
    # Gerar anos aleatórios
    yearFrom = random.randint(1990, 2020)
    yearTo = random.randint(yearFrom, 2024)
    
    # Outros campos
    stock = random.randint(1, 23)
    condition = random.choice(conditions)
    description = random.choice(descriptions)
    price = round(random.uniform(350.0, 3000.0), 2)
    
    product = {
        "vendedor": vendedor,
        "typeCategory": typeCategory,
        "typePart": typePart,
        "stock": stock,
        "carBrand": carBrand,
        "carModel": carModel,
        "yearFrom": yearFrom,
        "yearTo": yearTo,
        "condition": condition,
        "description": description,
        "price": price,
    }
    
    return product

# Gerar e inserir produtos
num_products = 33  #  quantos produtos deseja gerar

products_to_insert = [generate_random_product() for _ in range(num_products)]

result = collection.insert_many(products_to_insert)

print(f"Inseridos {len(result.inserted_ids)} produtos no banco de dados.")